webpack-contrib/install-webpack-plugin

- src/installer.js
- test/installer.test.js
The whole dependency name check was excluding imports which use `/` for deep imports - replaced it with a check for a leading `.`
Also ensured `check()` will only return a missing module name once. This probably doesn't matter for generating the npm install command, but also saves duplicating the same filesystem checks.
> Support deep imports and multiple imports from the same module

- README.md
- package.json
- src/installer.js
- src/loader.js
- test/installer.test.js
- test/loader.test.js
This would save the need for another dotfile.
Amazing loader idea, this is going to make for such a sweet development experience :+1:
> Use --save or --save-exact flags when installing based on loader query config

- package.json
- src/installer.js
- test/installer.test.js
Using v1.1.0, nothing was being installed on Windows:
```
Installing missing dependencies react-fa...
webpack built 73575fc7beab59bb5df5 in 3198ms
<webpack build error logging due to missing dependency>
```
After this change:
```
Installing missing dependencies react-fa...
react-fa@4.0.0 node_modules\react-fa
└── font-awesome@4.5.0
webpack built ce9ffcc706e95ddbf288 in 7675ms
```
> Fix spawning npm on Windows

- src/installer.js
Small things which would drive me to distraction over time :smile:
> Tweak logging of installation info

- src/plugin.js
- test/plugin.test.js
In the README.md there is an example on how to configure this plugin. 
```
plugins: [
new NpmInstallPlugin({
...
cacheMin: 999999  // --cache-min=999999 (prefer NPM cached version)
registry: "..."   // --registry="..."
save: true,       // --save
saveDev: true,    // --save-dev
saveExact: true,  // --save-exact
...
}),
]
```
However in the code these options are assumed to be located on a `cli` property. https://github.com/ericclemmons/npm-install-webpack-plugin/blob/master/src/plugin.js#L33
I assume one is outdated and should be updated. I can create a PR for this but I would first need to know where the change should be done.
> Mismatch between code and documentation

- example/webpack.config.babel.js
- src/plugin.js
- test/plugin.test.js
This plugin is awesome. My pain is all in the "Why" section in the readme :+1:
But why do I get `installing babel` when I use the plugin for the first time?
- the module babel itself seems to be deprecated, in favor of babel-cli & babel-core
- except babel-polyfill, babel-loader, etc, I didn't import babel in my code at all
Thanks!
> Support loader shorthand (e.g. "babel" vs. "babel-loader")

- example/lib/App/index.js
- src/installer.js
Re-reporting from insin/nwb#77, which would have been using v2, but I just checked this doesn't work in v3 in the development branch.
The external module check doesn't allow for package names which contain a period: https://github.com/ericclemmons/npm-install-webpack-plugin/blob/ea64307766ee31c0f4b314ad27d0c717471373a1/src/installer.js#L8
> Support installation of packages with a period in their name, e.g. lodash.random

- src/installer.js
- src/plugin.js
Can be useful when you're quickly testing something, and not actually building an app.
> Initialize missing `package.json`

- src/installer.js
When using this webpack plugin in a project using `@cycle/core` which has `rx` as peer dependency I met an infinite loop:
```bash
node_modules/.bin/webpack
ts-loader: Using typescript@1.8.10 and /Users/chadrien/src/ml/tsconfig.json
Installing `@cycle/core`...
/Users/chadrien/src/ml
├── @cycle/core@6.0.3  extraneous
└── UNMET PEER DEPENDENCY rx@*
npm WARN @cycle/core@6.0.3 requires a peer of rx@* but none was installed.
npm WARN ml No description
npm WARN ml No repository field.
npm WARN ml No license field.
Installing `@cycle/core`...
/Users/chadrien/src/ml
├── @cycle/core@6.0.3  extraneous
└── UNMET PEER DEPENDENCY rx@*
npm WARN @cycle/core@6.0.3 requires a peer of rx@* but none was installed.
npm WARN ml No description
npm WARN ml No repository field.
npm WARN ml No license field. …
```
> Install peerDependencies

- src/installer.js
- src/plugin.js
- test/installer.test.js
- test/plugin.test.js
Hi,
I'm getting reports about reduced performance. Here's the [thread](http://survivejs.com/webpack_react/webpack_and_react/#comment-2664052295).
Quote:
> I was experiencing slow bundle times as well. Running on OSX 10.10.5.
> After playing around with it for a bit, I noticed that removing the NpmInstallPlugin decreased my bundle time from about 6 seconds to less than a second, when making changes to the app.
Relevant setup can be found [here](https://github.com/survivejs/webpack_react/tree/0c19e26f037a78e21afee3db8f07b1de65cdec7c/project_source/02_developing_with_webpack/kanban_app).
Let me know if you need more information.
> Performance

- src/installer.js
- src/plugin.js
- test/installer.test.js
I noticed that if you try to import a npm package that doesn't even exist (say you do `import Notes from 'Notes.jsx';`), npm-install-webpack-plugin will still kick in. It might be preferable to handle this some other way (skip install, warn somehow?).
> Warn on missing NPM packages

- README.md
- example/webpack1-dev-server/webpack.config.defaults.js
- example/webpack1/webpack.config.defaults.js
- example/webpack2/webpack.config.defaults.js
- src/installer.js
- src/plugin.js
- test/installer.test.js
- test/plugin.test.js
Use case: allowing configuration of the `npm install` options used to vary based on the module missing dependencies were detected in.
This is pretty niche, but would be neat DX touch for tooling which can auto-configure it for you.
e.g. if installation is triggered by a module under `src/`, use `--save`; a module under `test/`, use `--save-dev`
Potential API (which suits a plugin, as it would otherwise need to be top-levelled in webpack config for a loader): pass a RegExp as `save`/`saveDev` config which is tested against the relative path from `process.cwd()` to the module the current install is being triggered from:
```js
cli: {
save: /^src\//,
saveDev: /^test\//
}
```
Alternatively, allow `cli` or any of its props to be a Function which would take a `module` arg similar to the …
> New Options (dev, peerDependencies)

- package.json
- src/installer.js
- test/installer.test.js
npm-install-webpack-plugin v4.0.0 / Node v4.4.5 / npm v2.14.16 / Windows 10 Home 64-bit
Before:
```
C:\Users\Jonny\tmp\serve-react>nwb serve-react app.js --auto-install
nwb: serve-react
Initializing `package.json`...
Usage: npm <command>
```
After:
```
C:\Users\Jonny\tmp\serve-react>nwb serve-react app.js --auto-install
nwb: serve-react
Initializing `package.json`...
Wrote to C:\Users\Jonny\tmp\serve-react\package.json:
```
> Fix failure to initialise package.json in Windows

- src/installer.js
- src/plugin.js
I'm using `babel-loader` as `babel-loader` in my webpack config instead of just `babel`. The plugin seems to be trying to install `babel-loader-loader`.
Which is probably the same for others, but haven't tested.
> Tries to install `babel-loader-loader`

- package.json
- src/plugin.js
- test/plugin.test.js
Resolvers are created later in the process in Webpack 2 - they're `null` if you try to access them in `apply()`.
This makes the plugin work for me while testing the Webpack 2 version of nwb.
This should also fix #88
> Use after-resolvers to hook into resolution

- example/webpack2/.babelrc
- example/webpack2/package.json
- example/webpack2/src/client.js
- example/webpack2/webpack.config.client.js
- example/webpack2/webpack.config.defaults.js
- package.json
- src/installer.js
- src/plugin.js
- src/utils.js
- test/installer.test.js
- test/plugin.test.js
- test/utils.test.js
I have no idea if this is the *correct* approach for this, as I've not personally ever made use of `NpmInstallPlugin` for loaders before and I don't really know what Webpack is doing under there, but it fixes #91 for me locally when I have `resolveLoader` config which allows webpack to resolve html-webpack-plugin's loader.
If this does the trick, I can update the failing tests to test the new implementation.
> Give webpack a shot at resolving loaders first

- README.md
- package.json
- Updates `README.md` to cover both the Standards effort and the JSF Maintainers effort
- Changes coverage to `webpack-contrib` codecov.io
- Repo token added to Travis env vars
- Updates badges to reflect move to `webpack-contrib`
> docs(readme): updates for JSF maintainers

- LICENSE
The license in this repo needs to be updated at the request of the foundation.
The `LICENSE` needs to be named `LICENSE` ( no extension ) if it isn't already.
The `LICENSE` needs to have the following copy.
```
Copyright JS Foundation and other contributors
Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
'Software'), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:
The above copyright notice and this permission notice shall be
included in all copies or substantial …
```
> JavaScript Foundation License

- README.md
- package.json
- src/installer.js
- src/plugin.js
- test/plugin.test.js
some company has their own npm command with a different name ,like tnpm ,cnpm and so on.
> feat: support custom npm clients (`options.npm`)

- README.md
This link was causing builds to fail on webpack.js.org. You probably want to resolve whatever the core issue is and add it back but this a temporary fix for now.
> docs(README): remove broken link

- src/installer.js
- test/installer.test.js
I've taken a stab at adding yarn as an option. I wanted to make it very explicit what the state of the command's config should be when `yarn` vs `npm`, but am open to a different way of discerning between the two.
I also mirrored the tests that already existed for `npm`, but for `yarn`. Let me know if I missed anything there!
As requested in #76, I exposed yarn by adding a `yarn` option. When true, it goes down the yarn path, otherwise, uses the same npm path. So an example usage would be:
```javascript
new NpmInstallPlugin({
yarn: true
});
```
This should resolve #76.
> feat: add `yarn` integration

- package.json
- src/plugin.js
I'm wondering if the note about `Compiler.options` in the Webpack 4 release notes only applies to loaders.
PR for #122 
Basic functionality working for me in the Webpack 4 version of nwb:
> Webpack 4 (only) compatibility

- src/installer.js
- test/installer.test.js
Currently, the default `babel` packages name used are outdated and not supported anymore. Fixed them by using the new names
> follow up of #130
> chore: fixed the pkg names

- .editorconfig
- .eslintignore
- .eslintrc.js
- .gitattributes
- .gitignore
- .prettierignore
- .prettierrc.js
- .travis.yml
- README.md
- index.js
- package-lock.json
- package.json
- src/installer.js
- src/plugin.js
- src/utils.js
- test/installer.test.js
- test/plugin.test.js
- test/utils.test.js
This PR contains
- eslint config
- prettier config
- linting and pretesting scripts
- lockfiles update (opt-in-out)
- formatting and linting fixes to the `src` and `test` folder
> chore : added eslint prettier with webpack-defaults standard

- package-lock.json
- package.json
- src/plugin.js
- test/plugin.test.js
feat
updated existing, will be adding more in future
yet to
**Summary**
Make the plugin compatible with webpack v5
yep, dropped support for old versions
> feat: migrate to webpack v5

- src/installer.js
- src/options.json
- test/__snapshots__/installer.test.js.snap
- test/__snapshots__/plugin.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/installer.test.js
- test/plugin.test.js
- test/validate-options.test.js
feature
Yes
No
**Summary**
Allow passing more arguments to the package manager.
Yes, `options.quiet` was removed in favor of `packageManager.options.quiet`
No
> feat: allow to set custom arguments for package manager
