webpack-contrib/install-webpack-plugin

- test/loader.test.js
- test/parser.test.js
> 100% Coverage

- package.json
```
├── CHANGELOG.md
├── LICENSE
├── README.md
├── index.js
├── node_modules
│   └── babel-core
├── package.json
├── src
│   ├── installer.js
│   ├── loader.js
│   └── parser.js
└── test
├── installer.test.js
├── loader.test.js
└── parser.test.js
```
And `.nvmrc`, `.travis.yml`, etc. is in here!
> Whitelist package.json "files"

- README.md
- package.json
- test/plugin.test.js
This is necessary for the 3.1.0 release.
> Passing tests + README

- src/installer.js
- test/installer.test.js
This is an alternative to #51 with fewer dependencies (and it still installs the dep!).
> Install peerDependency without version when given a range

- package.json
- src/installer.js
- src/plugin.js
- test/installer.test.js
- test/plugin.test.js
Package.json can now be optional, so don't create it and only save to it when available
---
Creating this to see what #80 and #92 look like together
> Check if modules are resolvable without consulting package.json

- README.md
- src/installer.js
- test/installer.test.js
- test/plugin.test.js
This won't actually make initialising `package.json` quiet yet due to an npm issue:
https://github.com/npm/npm/issues/15425
> Add a quiet option

- src/installer.js
Added
```js
try {
var babelConfigJs = require.resolve(path.resolve("babel.config.js"));
var babelOpts = require(babelConfigJs);
} catch (e2) {
console.info("couldn't locate babel.config.js nor .babelrc");
} finally {
}
```
In order to resolve babel's new config file format
> chore: added support for babel.config.js

- package.json
- src/plugin.js
PR contains
- Migrate from `memory-fs` to `memfs`
- added lockfiles
> chore: migrate from memory-fs to Memfs

- .github/FUNDING.yml
Added the configuration file to show up sponsorship information.
> Meta: Added sponsor button

- .github/CONTRIBUTING.md
- README.md
- Created the contributing docs.
- Included a dedicated section within `README` with a reference to the respective doc that people might miss out if otherwise.
> [Docs]: Added reference to contributing guidelines

- package-lock.json
- Fix security vulnerabilities
- Use lock file `v2`.
> chore(deps): fix security vulnerabilities

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
> chore: add issue and pr templates

- .github/workflows/nodejs.yml
Build
No
No
**Summary**
Everywhere else we have npm usage.
No
No
> build: use npm

- .github/dependabot.yml
chore
NA
NA
**Summary**
create `depandabot.yml`
No
No
> chore: add depandabot.yml

- .husky/commit-msg
NA
NA
**Summary**
https://typicode.github.io/husky/#/?id=husky_git_params-ie-commitlint-
No
No
> fix: update husky config

- index.js
- package-lock.json
- package.json
chore
no
no
**Summary**
Fix #173 
no
no
> chore: update eslint-plugin-import

- package-lock.json
- package.json
- test/installer.test.js
- test/plugin.test.js
- test/utils.test.js
chore
Updates test suite.
N/A
**Summary**
`expect` has been donated to `Jest`.
https://github.com/facebook/jest/issues/1679
No
N/A
> chore: remove `expect` in favor of the in-house solution

- package-lock.json
- package.json
chore
N/A
N/A
**Summary**
There aren't any breaking changes made to the API with the latest release.
No
N/A
> chore: update dependencies to the latest release

- README.md
- example/webpack1-dev-server/README.md
- example/webpack1-dev-server/webpack.config.defaults.js
- example/webpack1/README.md
- example/webpack1/webpack.config.defaults.js
- example/webpack2/README.md
- example/webpack2/webpack.config.defaults.js
- package.json
- src/plugin.js
update name
NA
Yes
**Summary**
Update name to `auto-install-webpack-plugin`
Yes
> chore: update plugin name to `auto-install-webpack-plugin`

- .github/CONTRIBUTING.md
- .github/workflows/nodejs.yml
- README.md
- example/webpack1-dev-server/lib/App/index.js
- example/webpack1-dev-server/package.json
- example/webpack1/lib/App/index.js
- example/webpack1/package.json
- example/webpack2/lib/App/index.js
- example/webpack2/package.json
- package.json
chore
NA
NA
**Summary**
update workflow name.
No
No
> chore: update workflow name

- .github/workflows/nodejs.yml
update ci
Already present
NA
**Summary**
Update CI to use webpack 5. Follow up https://github.com/webpack-contrib/install-webpack-plugin/pull/177
> ci: update to use webpack v5

- src/installer.js
- src/plugin.js
- test/__snapshots__/plugin.test.js.snap
- test/installer.test.js
- test/plugin.test.js
feat, refactor
Yes
No
**Summary**
fixes #94 
Maybe
No
> feat: use built in webpack logger

- package-lock.json
- package.json
- src/installer.js
- src/options.json
- src/plugin.js
- test/__snapshots__/plugin.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/plugin.test.js
- test/validate-options.test.js
feat
yes
No
**Summary**
add Schema
Yes, `npm` option is now boolean.
No
> feat: add schema

- src/installer.js
- src/options.json
- src/plugin.js
- test/__snapshots__/installer.test.js.snap
- test/__snapshots__/plugin.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/installer.test.js
- test/plugin.test.js
- test/validate-options.test.js
refactor
Yes
Not yet, will update docs after all refactor.
**Summary**
refactor schema, move `dev` and `peerDependencies` to `dependencies` option.
Yes, `dev` and `peerDependencies` were removed in favor of `dependencies.dev` and `dependencies.peer`
No
> refactor: add `dependencies` option

- src/installer.js
- src/options.json
- src/plugin.js
- test/__snapshots__/plugin.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/installer.test.js
- test/plugin.test.js
- test/validate-options.test.js
refactor
Yes
No
**Summary**
add `packageManager` option.
`packageManager: 'npm' | 'yarn' | { type: 'npm' | 'yarn' , options: { dev: boolean } } | (request, path) => { type: 'npm' | 'yarn', options: { dev: boolean }
`
Yes
`pnpm` is not yet supported.
> refactor: add `packageManager` option

- src/installer.js
- src/options.json
- test/__snapshots__/installer.test.js.snap
- test/__snapshots__/validate-options.test.js.snap
- test/installer.test.js
- test/validate-options.test.js
feature
yes
no
**Summary**
Add `pnpm` support for installing deps.
No
No
> feat: add pnpm support

- src/options.json
- test/__snapshots__/validate-options.test.js.snap
- test/validate-options.test.js
refactor
No
No
**Summary**
update schema removes stale properties.
yes
No
> refactor: remove stale properties from schema

- .eslintrc.js
- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/dependabot.yml
- .github/workflows/nodejs.yml
- .prettierrc.js
- commitlint.config.js
- index.js
- jest.config.js
- lint-staged.config.js
- src/installer.js
- src/plugin.js
- src/utils.js
- test/installer.test.js
- test/plugin.test.js
- test/utils.test.js
- test/validate-options.test.js
code style
NA
NA
**Summary**
use prettier defaults.
No
No
> style: use prettier defaults

- src/options.json
- test/__snapshots__/validate-options.test.js.snap
fix
Yes updated snaps
No
**Summary**
Improve descriptions for options.
No
No
> fix: improve descriptions

- README.md
Docs
No
Yes
**Summary**
Update documentation.
No
No
> docs: udpate

- .github/workflows/nodejs.yml
build, CI
NA
NA
**Summary**
Add `commitlint` check on CI.
No
No
> ci: add `commitlint` check

- package-lock.json
- package.json
- test/__snapshots__/validate-options.test.js.snap
chore
Updated snapshot
No
**Summary**
update schema-utils, Fix #218 
NO
No
> chore: update schema-utils

- .github/workflows/nodejs.yml
- src/plugin.js
- test/installer.test.js
build, CI
Already present
NA
**Summary**
Enable tests on node 16.
No
No
> feat: compatibility with node.js v16

- .github/workflows/nodejs.yml
ci
NA
No
**Summary**
use `actions/setup-node@v2`
No
No
> ci: use actions/setup-node@v2

- src/options.json
- test/__snapshots__/validate-options.test.js.snap
feature
Yes
No
**Summary**
add `link` in the schema to output docs link on errors.
No
No
> feat: add `link` in schema

- .eslintrc.js
- src/installer.js
- src/plugin.js
chore
No
No
**Summary**
fix lint warnings
No
No
> chore: fix lint warnings
